// ── Constants ─────────────────────────────────────────────────────────────────
const CASABLANCA_CENTER = { lat: 33.5731, lng: -7.5898 };

const ACTIVITY_TYPES = [
  { id: 'all',        label: 'All',        emoji: '✨' },
  { id: 'concert',   label: 'Concert',    emoji: '🎵' },
  { id: 'cinema',    label: 'Cinema',     emoji: '🎬' },
  { id: 'sports',    label: 'Sports',     emoji: '⚽' },
  { id: 'museum',    label: 'Museum',     emoji: '🏛️' },
  { id: 'outdoor',   label: 'Outdoor',    emoji: '🌿' },
  { id: 'festival',  label: 'Festival',   emoji: '🎉' },
  { id: 'exhibition',label: 'Exhibition', emoji: '🎨' },
];

// ── Activities (20 realistic Casablanca entries) ──────────────────────────────
const ACTIVITIES = [
  {
    id: 1,
    name: 'Mohammed V Stadium – Derby Match',
    type: 'sports', emoji: '⚽',
    venue: 'Stade Mohammed V',
    address: 'Av. des FAR, Casablanca',
    lat: 33.5856, lng: -7.6195,
    date: 'Sat, 8 Mar 2026', time: '18:00',
    price: 80, rating: 4.5,
    tags: ['sports','social','evening','outdoor','budget'],
    description: 'Wydad AC vs Raja CA – the legendary Casablanca derby at the iconic Stade Mohammed V. Unmissable atmosphere.',
  },
  {
    id: 2,
    name: 'Jazz Night at Anfa Place',
    type: 'concert', emoji: '🎷',
    venue: 'Anfa Place Living Resort',
    address: 'Bd de l\'Océan Atlantique, Casablanca',
    lat: 33.5921, lng: -7.6678,
    date: 'Fri, 7 Mar 2026', time: '21:00',
    price: 200, rating: 4.7,
    tags: ['music','social','evening','indoor','premium'],
    description: 'Smooth jazz featuring Moroccan and international artists with a stunning Atlantic Ocean backdrop.',
  },
  {
    id: 3,
    name: 'Megarama – Latest Blockbuster',
    type: 'cinema', emoji: '🎬',
    venue: 'Megarama Casablanca',
    address: 'Bd de la Résistance, Casablanca',
    lat: 33.5884, lng: -7.6114,
    date: 'Daily', time: 'Various',
    price: 70, rating: 4.3,
    tags: ['cinema','solo','indoor','budget'],
    description: 'Morocco\'s largest cinema complex — 14 screens, VIP seating, and the latest international releases.',
  },
  {
    id: 4,
    name: 'Hassan II Mosque – Guided Tour',
    type: 'museum', emoji: '🕌',
    venue: 'Mosquée Hassan II',
    address: 'Bd Sidi Mohammed Ben Abdallah',
    lat: 33.6086, lng: -7.6325,
    date: 'Sat–Thu', time: '09:00–17:00',
    price: 120, rating: 4.9,
    tags: ['arts','solo','indoor','daytime','budget'],
    description: 'Guided tour of the world\'s 7th-largest mosque — a masterpiece of Moorish architecture perched on the ocean.',
  },
  {
    id: 5,
    name: 'Corniche Walk & Beach',
    type: 'outdoor', emoji: '🏖️',
    venue: 'Ain Diab Corniche',
    address: 'Corniche Ain Diab, Casablanca',
    lat: 33.5929, lng: -7.6794,
    date: 'Every day', time: 'All day',
    price: 0, rating: 4.4,
    tags: ['outdoor','solo','social','daytime','free'],
    description: 'Stroll along Casablanca\'s famous beachfront promenade — cafés, ocean views, and fresh Atlantic breezes.',
  },
  {
    id: 6,
    name: 'Parc de la Ligue Arabe',
    type: 'outdoor', emoji: '🌳',
    venue: 'Parc de la Ligue Arabe',
    address: 'Bd Mohammed V, Casablanca',
    lat: 33.5892, lng: -7.6207,
    date: 'Every day', time: '06:00–21:00',
    price: 0, rating: 4.2,
    tags: ['outdoor','solo','family','daytime','free'],
    description: 'Casablanca\'s main public park — perfect for a morning jog, picnic, or a lazy afternoon under the palms.',
  },
  {
    id: 7,
    name: 'Villa des Arts – Contemporary Art',
    type: 'exhibition', emoji: '🎨',
    venue: 'Villa des Arts',
    address: 'Bd Brahim Roudani, Casablanca',
    lat: 33.5816, lng: -7.6244,
    date: 'Tue–Sat', time: '09:00–19:00',
    price: 20, rating: 4.6,
    tags: ['arts','solo','indoor','daytime','free'],
    description: 'Elegant early-20th-century villa hosting rotating contemporary Moroccan art exhibitions. Entry almost free.',
  },
  {
    id: 8,
    name: 'Casablanca Fashion Week',
    type: 'festival', emoji: '👗',
    venue: 'Morocco Mall',
    address: 'Bd de la Corniche, Casablanca',
    lat: 33.5876, lng: -7.6751,
    date: 'Sat, 14 Mar 2026', time: '14:00',
    price: 150, rating: 4.4,
    tags: ['social','indoor','daytime','premium','festival'],
    description: 'Morocco\'s premier fashion event at the iconic Morocco Mall — local and international designers on the runway.',
  },
  {
    id: 9,
    name: 'Harley Biker Rally – Ain Diab',
    type: 'festival', emoji: '🏍️',
    venue: 'Ain Diab Esplanade',
    address: 'Av. de l\'Armée Royale, Casablanca',
    lat: 33.5903, lng: -7.6821,
    date: 'Sun, 9 Mar 2026', time: '10:00',
    price: 0, rating: 4.3,
    tags: ['outdoor','social','daytime','free','festival'],
    description: 'Annual motorcycle gathering along the Ain Diab seafront — free to attend and a great spectacle.',
  },
  {
    id: 10,
    name: 'L\'Boulevard Urban Arts Festival',
    type: 'festival', emoji: '🎤',
    venue: 'Casablanca Complex',
    address: 'Quartier Industriel, Casablanca',
    lat: 33.5612, lng: -7.5937,
    date: 'Fri–Sun, 20–22 Mar 2026', time: '17:00',
    price: 100, rating: 4.8,
    tags: ['music','social','evening','outdoor','budget','festival'],
    description: 'Morocco\'s biggest urban arts festival — hip-hop, gnawa, jazz, and breathtaking street art. A city institution.',
  },
  {
    id: 11,
    name: 'Casablanca Half Marathon',
    type: 'sports', emoji: '🏃',
    venue: 'Parc de la Ligue Arabe (start)',
    address: 'Casablanca City Centre',
    lat: 33.5875, lng: -7.6189,
    date: 'Sun, 15 Mar 2026', time: '07:00',
    price: 50, rating: 4.5,
    tags: ['sports','outdoor','daytime','budget'],
    description: 'Join thousands of runners through Casablanca\'s most beautiful boulevards. All levels welcome.',
  },
  {
    id: 12,
    name: 'Rai Music Night – La Coupole',
    type: 'concert', emoji: '🎶',
    venue: 'Complexe culturel La Coupole',
    address: 'Rue Omar Slaoui, Casablanca',
    lat: 33.5945, lng: -7.6140,
    date: 'Thu, 12 Mar 2026', time: '20:30',
    price: 180, rating: 4.6,
    tags: ['music','social','evening','indoor','budget'],
    description: 'An electrifying evening of Algerian and Moroccan Rai music in Casablanca\'s historic cultural venue.',
  },
  {
    id: 13,
    name: 'Old Medina Exploration Walk',
    type: 'outdoor', emoji: '🧭',
    venue: 'Old Medina',
    address: 'Bd des Almohades, Casablanca',
    lat: 33.6031, lng: -7.6167,
    date: 'Every day', time: '08:00–18:00',
    price: 0, rating: 4.1,
    tags: ['outdoor','solo','daytime','free','arts'],
    description: 'Wander through Casablanca\'s charming old medina — souks, street food, and traditional Moroccan crafts.',
  },
  {
    id: 14,
    name: 'Beach Yoga – Ain Diab',
    type: 'sports', emoji: '🧘',
    venue: 'Ain Diab Beach',
    address: 'Corniche Ain Diab, Casablanca',
    lat: 33.5938, lng: -7.6814,
    date: 'Sat & Sun', time: '08:00',
    price: 0, rating: 4.4,
    tags: ['sports','outdoor','daytime','free','solo'],
    description: 'Free morning yoga and fitness sessions on the beach, run by local sports clubs. All levels welcome.',
  },
  {
    id: 15,
    name: 'Photography Exhibition – MACAAL',
    type: 'exhibition', emoji: '📷',
    venue: 'Musée d\'Art Contemporain',
    address: 'Bd Moulay Youssef, Casablanca',
    lat: 33.5824, lng: -7.6171,
    date: 'Tue–Sun', time: '10:00–18:00',
    price: 40, rating: 4.7,
    tags: ['arts','solo','indoor','daytime','budget'],
    description: 'World-class contemporary photography from African and Arab world artists in a beautiful gallery space.',
  },
  {
    id: 16,
    name: 'Night Market – Quartier Habous',
    type: 'festival', emoji: '🌙',
    venue: 'Quartier Habous',
    address: 'Rue de la Mosquée, Casablanca',
    lat: 33.5766, lng: -7.6094,
    date: 'Fri & Sat nights', time: '19:00–23:00',
    price: 0, rating: 4.5,
    tags: ['outdoor','social','evening','free','family'],
    description: 'Vibrant weekly night market in the New Medina — street food, artisan crafts, and live music.',
  },
  {
    id: 17,
    name: 'Electronic Music Night – Lighthouse',
    type: 'concert', emoji: '🎧',
    venue: 'Lighthouse Club',
    address: 'Corniche Ain Diab, Casablanca',
    lat: 33.5916, lng: -7.6902,
    date: 'Fri & Sat', time: '23:00',
    price: 250, rating: 4.4,
    tags: ['music','social','evening','indoor','premium'],
    description: 'International DJs, ocean views, and Casablanca\'s best sound system. The city\'s top electronic venue.',
  },
  {
    id: 18,
    name: 'Art Déco Architecture Walk',
    type: 'museum', emoji: '🏛️',
    venue: 'Art Déco District',
    address: 'Av. des FAR, Casablanca',
    lat: 33.5901, lng: -7.6133,
    date: 'Mon–Fri', time: '10:00–14:00',
    price: 150, rating: 4.6,
    tags: ['arts','solo','outdoor','daytime','budget'],
    description: 'Guided walking tour through Casablanca\'s Art Déco gems — the finest collection outside Europe.',
  },
  {
    id: 19,
    name: 'Rugby Match – Stade Larbi Zaouli',
    type: 'sports', emoji: '🏉',
    venue: 'Stade Larbi Zaouli',
    address: 'Mâarif, Casablanca',
    lat: 33.5693, lng: -7.6423,
    date: 'Sun, 8 Mar 2026', time: '15:00',
    price: 60, rating: 4.2,
    tags: ['sports','social','daytime','outdoor','budget'],
    description: 'International rugby test match at the modern Mâarif stadium. Great family atmosphere.',
  },
  {
    id: 20,
    name: 'Open Mic Night – Milk Bar',
    type: 'concert', emoji: '🎤',
    venue: 'Milk Bar Casablanca',
    address: 'Rue Mustapha El Maâni, Casablanca',
    lat: 33.5898, lng: -7.6219,
    date: 'Wed & Thu', time: '20:00',
    price: 0, rating: 4.3,
    tags: ['music','social','evening','indoor','free'],
    description: 'Intimate open mic sessions showcasing Casablanca\'s emerging talent. Free entry, great vibes.',
  },
];

// ── Quiz questions ────────────────────────────────────────────────────────────
const QUIZ_QUESTIONS = [
  {
    id: 1,
    question: "What's your vibe right now?",
    emoji: '✨',
    options: [
      { label: 'Chill & Relaxed',    emoji: '😌', tags: ['outdoor','solo','free','daytime'] },
      { label: 'Energetic & Pumped', emoji: '⚡', tags: ['sports','social','evening','outdoor'] },
      { label: 'Creative & Curious', emoji: '🎨', tags: ['arts','indoor','daytime','solo'] },
      { label: 'Social & Festive',   emoji: '🎉', tags: ['social','music','festival','evening'] },
    ],
  },
  {
    id: 2,
    question: 'Who are you going with?',
    emoji: '👥',
    options: [
      { label: 'Just me',         emoji: '🧍', tags: ['solo','arts','indoor'] },
      { label: 'With my partner', emoji: '💑', tags: ['premium','evening','indoor'] },
      { label: 'Small group',     emoji: '👫', tags: ['social','budget','outdoor'] },
      { label: 'The whole crew',  emoji: '🎊', tags: ['social','sports','festival','outdoor'] },
    ],
  },
  {
    id: 3,
    question: "What's your budget for tonight?",
    emoji: '💰',
    options: [
      { label: 'Free only',               emoji: '🆓', tags: ['free'] },
      { label: 'Budget (under 100 MAD)',  emoji: '💵', tags: ['budget','free'] },
      { label: 'Mid-range (100–300 MAD)', emoji: '💳', tags: ['budget','premium'] },
      { label: 'Treat myself!',           emoji: '✨', tags: ['premium'] },
    ],
  },
  {
    id: 4,
    question: 'Indoor or outdoor?',
    emoji: '🌍',
    options: [
      { label: 'Love the outdoors',   emoji: '🌿', tags: ['outdoor','daytime'] },
      { label: 'Cosy indoor vibes',   emoji: '🏠', tags: ['indoor'] },
      { label: 'Evening & nightlife', emoji: '🌙', tags: ['evening','indoor','social'] },
      { label: 'Whatever the weather',emoji: '🌤️', tags: ['outdoor','indoor','daytime'] },
    ],
  },
];

// ── Fallback restaurants (used if Overpass API fails) ─────────────────────────
const FALLBACK_RESTAURANTS = [
  { id:'f1', name:'La Sqala',          cuisine:'Moroccan',    lat:33.6064, lng:-7.6279, phone:'+212 522 260 960' },
  { id:'f2', name:'Rick\'s Café',      cuisine:'American/Moroccan', lat:33.6037, lng:-7.6278, phone:'+212 522 274 207' },
  { id:'f3', name:'Le Cabestan',       cuisine:'Seafood',     lat:33.5937, lng:-7.6677, phone:'+212 522 394 011' },
  { id:'f4', name:'Basmane',           cuisine:'Moroccan',    lat:33.5922, lng:-7.6645, phone:'+212 522 391 000' },
  { id:'f5', name:'Taj Mahal',         cuisine:'Indian',      lat:33.5883, lng:-7.6195, phone:null },
  { id:'f6', name:'Brasserie Bavaroise',cuisine:'French',     lat:33.5942, lng:-7.6200, phone:'+212 522 311 760' },
  { id:'f7', name:'Al-Mounia',         cuisine:'Moroccan',    lat:33.5901, lng:-7.6348, phone:'+212 522 222 669' },
  { id:'f8', name:'Le Buffet',         cuisine:'International',lat:33.5929, lng:-7.6192, phone:null },
  { id:'f9', name:'Sushiyama',         cuisine:'Japanese',    lat:33.5872, lng:-7.6540, phone:null },
  { id:'f10',name:'Paul Casablanca',   cuisine:'French Bakery',lat:33.5880, lng:-7.6754, phone:null },
  { id:'f11',name:'McDonald\'s Mâarif',cuisine:'Fast food',   lat:33.5714, lng:-7.6461, phone:null },
  { id:'f12',name:'La Bodega',         cuisine:'Spanish/Tapas',lat:33.5953, lng:-7.6141, phone:'+212 522 541 842' },
  { id:'f13',name:'Oceanfront Grill',  cuisine:'Seafood/Grill',lat:33.5941, lng:-7.6803, phone:null },
  { id:'f14',name:'Chez Paul',         cuisine:'French',      lat:33.5935, lng:-7.6212, phone:null },
  { id:'f15',name:'Le Petit Rocher',   cuisine:'Moroccan/International',lat:33.5894, lng:-7.6682, phone:'+212 522 794 626' },
];
